services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    volumes:
      - "./config/keycloak/import:/opt/keycloak/data/import"
    depends_on:
      - keycloak-db
    command:
      - start-dev
      - --import-realm
    networks:
      - app-network

  keycloak-db:
    image: postgres:17.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak_db
    volumes:
      - "/tmp/keycloak-db:/var/lib/postgresql/data"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge