server:
  port: 8081

spring:
  application:
    name: secure-app-test

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/test-realm

logging:
  level:
    org.springframework.security: DEBUG